apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  namespace: production
type: Opaque
stringData:
  DB_USERNAME: "laravel"
  DB_PASSWORD: "P@ssw0rd123!Secure"
  APP_KEY: "base64:yourbase64appkeyhere12345678901234567890="
