<?php

declare(strict_types=1);

return [
    'wakatime' => [
        'title' => 'Wakatime',
        'description' => 'Coding time panel',
        'url' => 'https://wakatime.com/dashboard',
        'heroicon' => 'heroicon-s-rocket-launch',
        'icon' => null,
        'group' => null,
        'sort' => 1,
    ],
    'nightwatch' => [
        'title' => 'Nightwatch',
        'description' => 'Laravel monitoring panel',
        'url' => 'https://nightwatch.laravel.com/us/environments/9f2c96aa-8c28-4e01-9385-a907a4853111/dashboard',
        'heroicon' => 'heroicon-s-bug-ant',
        'icon' => null,
        'group' => null,
        'sort' => 1,
    ],
    'github' => [
        'title' => 'Github',
        'description' => 'My github repository',
        'url' => 'https://github.com/moham7dreza',
        'heroicon' => 'heroicon-o-code-bracket',
        'icon' => null,
        'group' => null,
        'sort' => 1,
    ],
    'tools' => [
        'title' => 'Tools',
        'description' => 'Tools Page',
        'url' => '/tool',
        'heroicon' => 'heroicon-o-cube',
        'icon' => null,
        'group' => null,
        'sort' => 1,
    ],
    'front-root' => [
        'title' => 'Mainweb',
        'description' => 'Front-End Root Page',
        'url' => 'http://localhost:3000',
        'heroicon' => 'heroicon-o-building-storefront',
        'icon' => null,
        'group' => 'Links',
        'sort' => 1,
    ],
    'backend-root' => [
        'title' => 'Backend Root',
        'description' => 'Backend Root Page',
        'url' => '/',
        'heroicon' => 'heroicon-o-building-office',
        'icon' => null,
        'group' => 'Links',
        'sort' => 1,
    ],
    'chatify' => [
        'title' => 'Chatify',
        'description' => 'Chatify Page',
        'url' => '/chatify',
        'heroicon' => 'heroicon-o-chat-bubble-left-right',
        'icon' => null,
        'group' => 'Tools',
        'sort' => 1,
    ],
    'backend-admin' => [
        'title' => 'Super Admin Panel',
        'description' => 'Filament admin panel',
        'url' => '/super-admin',
        'heroicon' => 'heroicon-o-academic-cap',
        'icon' => null,
        'group' => 'Links',
        'sort' => 1,
    ],
    'user-panel' => [
        'title' => 'User Panel',
        'description' => 'Front-End user panel',
        'url' => config('app.frontend_url').'/admin',
        'heroicon' => 'heroicon-o-home-modern',
        'icon' => null,
        'group' => 'Links',
        'sort' => 1,
    ],
    'api-doc' => [
        'title' => 'Api Docs',
        'description' => 'API Docs',
        'url' => '/docs/api',
        'heroicon' => 'heroicon-o-command-line',
        'icon' => null,
        'group' => 'Tools',
        'sort' => 2,
    ],
    'health' => [
        'title' => 'Monitoring',
        'description' => 'Health monitoring panel',
        'url' => '/health?fresh',
        'heroicon' => 'heroicon-o-beaker',
        'icon' => null,
        'group' => 'Tools',
        'sort' => 3,
    ],
    'log-viewer' => [
        'title' => 'Logging',
        'description' => 'Log Viewer',
        'url' => '/log-viewer',
        'heroicon' => 'heroicon-o-exclamation-triangle',
        'icon' => null,
        'group' => 'Tools',
        'sort' => 4,
    ],
    'telescope' => [
        'title' => 'Telescope',
        'description' => 'Monitoring Telescope panel',
        'url' => '/telescope',
        'heroicon' => 'heroicon-o-magnifying-glass-circle',
        'icon' => null,
        'group' => 'Tools',
        'sort' => 5,
    ],
    'horizon' => [
        'title' => 'Horizon',
        'description' => 'Horizon panel',
        'url' => '/horizon',
        'heroicon' => 'heroicon-o-queue-list',
        'icon' => null,
        'group' => 'Tools',
        'sort' => 6,
    ],
    'pulse' => [
        'title' => 'Pulse',
        'description' => 'Pulse panel',
        'url' => '/pulse',
        'heroicon' => 'heroicon-o-arrow-trending-up',
        'icon' => null,
        'group' => 'Tools',
        'sort' => 7,
    ],
    'prometheus' => [
        'title' => 'Metrics',
        'description' => 'Prometheus metrics exports',
        'url' => '/metrics',
        'heroicon' => 'heroicon-o-rss',
        'icon' => null,
        'group' => 'Tools',
        'sort' => 8,
    ],
    'spy' => [
        'title' => 'SPY',
        'description' => 'Http requests panel',
        'url' => '/spy',
        'heroicon' => 'heroicon-o-arrow-top-right-on-square',
        'icon' => null,
        'group' => 'Tools',
        'sort' => 9,
    ],
    'analytics' => [
        'title' => 'Analytics',
        'description' => 'Laravel requests analytics panel',
        'url' => '/analytics',
        'heroicon' => 'heroicon-o-chart-bar',
        'icon' => null,
        'group' => 'Tools',
        'sort' => 10,
    ],
    'activitylog-ui' => [
        'title' => 'Activity Logs',
        'description' => 'Activity Log UI panel',
        'url' => '/activitylog-ui',
        'heroicon' => 'heroicon-o-folder-open',
        'icon' => null,
        'group' => 'Tools',
        'sort' => 11,
    ],
    'vantage' => [
        'title' => 'Vantage',
        'description' => 'Tracks and monitors your queue jobs',
        'url' => '/vantage',
        'heroicon' => 'heroicon-o-square-3-stack-3d',
        'icon' => null,
        'group' => 'Tools',
        'sort' => 12,
    ],
    'ghost-notes' => [
        'title' => 'Ghost Notes',
        'description' => 'Transform Code Comments into a Dev Diary',
        'url' => '/ghost-notes',
        'heroicon' => 'heroicon-o-pencil-square',
        'icon' => null,
        'group' => 'Tools',
        'sort' => 13,
    ],
];
